/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'view-asset': RouteRecordInfo<'view-asset', '/assets/:assetId/:fileId?', { assetId: ParamValue<true>, fileId?: ParamValueZeroOrOne<true> }, { assetId: ParamValue<false>, fileId?: ParamValueZeroOrOne<false> }>,
    '/files/[fileId]': RouteRecordInfo<'/files/[fileId]', '/files/:fileId', { fileId: ParamValue<true> }, { fileId: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'projects-list': RouteRecordInfo<'projects-list', '/projects', Record<never, never>, Record<never, never>>,
    'view-project': RouteRecordInfo<'view-project', '/projects/:projectId', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
  }
}
