/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'projects-list': RouteRecordInfo<'projects-list', '/projects', Record<never, never>, Record<never, never>>,
    'project-root': RouteRecordInfo<'project-root', '/projects/:projectId', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project-assets': RouteRecordInfo<'project-assets', '/projects/:projectId/assets', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project-gallery': RouteRecordInfo<'project-gallery', '/projects/:projectId/gallery', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'project-main': RouteRecordInfo<'project-main', '/projects/:projectId/main', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
  }
}
