/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'app-home': RouteRecordInfo<'app-home', '/', Record<never, never>, Record<never, never>>,
    'file': RouteRecordInfo<'file', '/files/:sha256', { sha256: ParamValue<true> }, { sha256: ParamValue<false> }>,
    'project': RouteRecordInfo<'project', '/projects/:projectId', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
  }
}
