/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAsset200Response,
  CreateAssetRequest,
  GetPublicAccessUrl200Response,
  SignIn200Response,
} from '../models/index';

export interface CreateAssetOperationRequest {
    CreateAssetRequest: CreateAssetRequest;
}

export interface GetFileUploadUrlRequest {
    fileName: string;
    sha256: string;
    contentType: string;
    createdAt: number;
    assetId: string;
    fileClass: string;
}

export interface GetPublicAccessUrlRequest {
    assetId: string;
    fileClass: string;
}

export interface MarkFileAsUploadedRequest {
    assetId: string;
    fileClass: string;
}

/**
 * AssetsApi - interface
 * 
 * @export
 * @interface AssetsApiInterface
 */
export interface AssetsApiInterface {
    /**
     * 
     * @summary createAsset
     * @param {CreateAssetRequest} CreateAssetRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetsApiInterface
     */
    createAssetRaw(requestParameters: CreateAssetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAsset200Response>>;

    /**
     * createAsset
     */
    createAsset(requestParameters: CreateAssetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAsset200Response>;

    /**
     * 
     * @summary getFileUploadUrl
     * @param {string} fileName 
     * @param {string} sha256 
     * @param {string} contentType 
     * @param {number} createdAt 
     * @param {string} assetId 
     * @param {string} fileClass 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetsApiInterface
     */
    getFileUploadUrlRaw(requestParameters: GetFileUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPublicAccessUrl200Response>>;

    /**
     * getFileUploadUrl
     */
    getFileUploadUrl(requestParameters: GetFileUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPublicAccessUrl200Response>;

    /**
     * 
     * @summary getPublicAccessUrl
     * @param {string} assetId 
     * @param {string} fileClass 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetsApiInterface
     */
    getPublicAccessUrlRaw(requestParameters: GetPublicAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPublicAccessUrl200Response>>;

    /**
     * getPublicAccessUrl
     */
    getPublicAccessUrl(requestParameters: GetPublicAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPublicAccessUrl200Response>;

    /**
     * 
     * @summary markFileAsUploaded
     * @param {string} assetId 
     * @param {string} fileClass 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetsApiInterface
     */
    markFileAsUploadedRaw(requestParameters: MarkFileAsUploadedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * markFileAsUploaded
     */
    markFileAsUploaded(requestParameters: MarkFileAsUploadedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

}

/**
 * 
 */
export class AssetsApi extends runtime.BaseAPI implements AssetsApiInterface {

    /**
     * createAsset
     */
    async createAssetRaw(requestParameters: CreateAssetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAsset200Response>> {
        if (requestParameters['CreateAssetRequest'] == null) {
            throw new runtime.RequiredError(
                'CreateAssetRequest',
                'Required parameter "CreateAssetRequest" was null or undefined when calling createAsset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/assets`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['CreateAssetRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * createAsset
     */
    async createAsset(requestParameters: CreateAssetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAsset200Response> {
        const response = await this.createAssetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getFileUploadUrl
     */
    async getFileUploadUrlRaw(requestParameters: GetFileUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPublicAccessUrl200Response>> {
        if (requestParameters['fileName'] == null) {
            throw new runtime.RequiredError(
                'fileName',
                'Required parameter "fileName" was null or undefined when calling getFileUploadUrl().'
            );
        }

        if (requestParameters['sha256'] == null) {
            throw new runtime.RequiredError(
                'sha256',
                'Required parameter "sha256" was null or undefined when calling getFileUploadUrl().'
            );
        }

        if (requestParameters['contentType'] == null) {
            throw new runtime.RequiredError(
                'contentType',
                'Required parameter "contentType" was null or undefined when calling getFileUploadUrl().'
            );
        }

        if (requestParameters['createdAt'] == null) {
            throw new runtime.RequiredError(
                'createdAt',
                'Required parameter "createdAt" was null or undefined when calling getFileUploadUrl().'
            );
        }

        if (requestParameters['assetId'] == null) {
            throw new runtime.RequiredError(
                'assetId',
                'Required parameter "assetId" was null or undefined when calling getFileUploadUrl().'
            );
        }

        if (requestParameters['fileClass'] == null) {
            throw new runtime.RequiredError(
                'fileClass',
                'Required parameter "fileClass" was null or undefined when calling getFileUploadUrl().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fileName'] != null) {
            queryParameters['fileName'] = requestParameters['fileName'];
        }

        if (requestParameters['sha256'] != null) {
            queryParameters['sha256'] = requestParameters['sha256'];
        }

        if (requestParameters['contentType'] != null) {
            queryParameters['contentType'] = requestParameters['contentType'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['createdAt'] = requestParameters['createdAt'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/assets/{assetId}/files/{fileClass}`.replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters['assetId']))).replace(`{${"fileClass"}}`, encodeURIComponent(String(requestParameters['fileClass']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getFileUploadUrl
     */
    async getFileUploadUrl(requestParameters: GetFileUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPublicAccessUrl200Response> {
        const response = await this.getFileUploadUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getPublicAccessUrl
     */
    async getPublicAccessUrlRaw(requestParameters: GetPublicAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPublicAccessUrl200Response>> {
        if (requestParameters['assetId'] == null) {
            throw new runtime.RequiredError(
                'assetId',
                'Required parameter "assetId" was null or undefined when calling getPublicAccessUrl().'
            );
        }

        if (requestParameters['fileClass'] == null) {
            throw new runtime.RequiredError(
                'fileClass',
                'Required parameter "fileClass" was null or undefined when calling getPublicAccessUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/assets/{assetId}/files/{fileClass}`.replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters['assetId']))).replace(`{${"fileClass"}}`, encodeURIComponent(String(requestParameters['fileClass']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getPublicAccessUrl
     */
    async getPublicAccessUrl(requestParameters: GetPublicAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPublicAccessUrl200Response> {
        const response = await this.getPublicAccessUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * markFileAsUploaded
     */
    async markFileAsUploadedRaw(requestParameters: MarkFileAsUploadedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['assetId'] == null) {
            throw new runtime.RequiredError(
                'assetId',
                'Required parameter "assetId" was null or undefined when calling markFileAsUploaded().'
            );
        }

        if (requestParameters['fileClass'] == null) {
            throw new runtime.RequiredError(
                'fileClass',
                'Required parameter "fileClass" was null or undefined when calling markFileAsUploaded().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/assets/{assetId}/files/{fileClass}/`.replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters['assetId']))).replace(`{${"fileClass"}}`, encodeURIComponent(String(requestParameters['fileClass']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * markFileAsUploaded
     */
    async markFileAsUploaded(requestParameters: MarkFileAsUploadedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.markFileAsUploadedRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
