/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Collection,
  CreateCollection200Response,
  CreateCollectionRequest,
  Project,
  SignIn200Response,
  UpdateCollectionRequest,
} from '../models/index';

export interface AddProjectToCollectionRequest {
    collectionId: string;
    projectId: string;
}

export interface CreateCollectionOperationRequest {
    CreateCollectionRequest: CreateCollectionRequest;
}

export interface GetProjectsInCollectionRequest {
    collectionId: string;
}

export interface RemoveProjectFromCollectionRequest {
    collectionId: string;
    projectId: string;
}

export interface UpdateCollectionOperationRequest {
    collectionId: string;
    UpdateCollectionRequest: UpdateCollectionRequest;
}

/**
 * CollectionsApi - interface
 * 
 * @export
 * @interface CollectionsApiInterface
 */
export interface CollectionsApiInterface {
    /**
     * 
     * @summary addProjectToCollection
     * @param {string} collectionId 
     * @param {string} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApiInterface
     */
    addProjectToCollectionRaw(requestParameters: AddProjectToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * addProjectToCollection
     */
    addProjectToCollection(requestParameters: AddProjectToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary createCollection
     * @param {CreateCollectionRequest} CreateCollectionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApiInterface
     */
    createCollectionRaw(requestParameters: CreateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCollection200Response>>;

    /**
     * createCollection
     */
    createCollection(requestParameters: CreateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCollection200Response>;

    /**
     * 
     * @summary getCollections
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApiInterface
     */
    getCollectionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Collection>>>;

    /**
     * getCollections
     */
    getCollections(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Collection>>;

    /**
     * 
     * @summary getProjectsInCollection
     * @param {string} collectionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApiInterface
     */
    getProjectsInCollectionRaw(requestParameters: GetProjectsInCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>>;

    /**
     * getProjectsInCollection
     */
    getProjectsInCollection(requestParameters: GetProjectsInCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>>;

    /**
     * 
     * @summary removeProjectFromCollection
     * @param {string} collectionId 
     * @param {string} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApiInterface
     */
    removeProjectFromCollectionRaw(requestParameters: RemoveProjectFromCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * removeProjectFromCollection
     */
    removeProjectFromCollection(requestParameters: RemoveProjectFromCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary updateCollection
     * @param {string} collectionId 
     * @param {UpdateCollectionRequest} UpdateCollectionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionsApiInterface
     */
    updateCollectionRaw(requestParameters: UpdateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * updateCollection
     */
    updateCollection(requestParameters: UpdateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

}

/**
 * 
 */
export class CollectionsApi extends runtime.BaseAPI implements CollectionsApiInterface {

    /**
     * addProjectToCollection
     */
    async addProjectToCollectionRaw(requestParameters: AddProjectToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling addProjectToCollection().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addProjectToCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/collections/{collectionId}/projects/{projectId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * addProjectToCollection
     */
    async addProjectToCollection(requestParameters: AddProjectToCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.addProjectToCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * createCollection
     */
    async createCollectionRaw(requestParameters: CreateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCollection200Response>> {
        if (requestParameters['CreateCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'CreateCollectionRequest',
                'Required parameter "CreateCollectionRequest" was null or undefined when calling createCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/collections`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['CreateCollectionRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * createCollection
     */
    async createCollection(requestParameters: CreateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCollection200Response> {
        const response = await this.createCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getCollections
     */
    async getCollectionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Collection>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/collections`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getCollections
     */
    async getCollections(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Collection>> {
        const response = await this.getCollectionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * getProjectsInCollection
     */
    async getProjectsInCollectionRaw(requestParameters: GetProjectsInCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling getProjectsInCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/collections/{collectionId}/projects`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getProjectsInCollection
     */
    async getProjectsInCollection(requestParameters: GetProjectsInCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>> {
        const response = await this.getProjectsInCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * removeProjectFromCollection
     */
    async removeProjectFromCollectionRaw(requestParameters: RemoveProjectFromCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling removeProjectFromCollection().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling removeProjectFromCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/collections/{collectionId}/projects/{projectId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * removeProjectFromCollection
     */
    async removeProjectFromCollection(requestParameters: RemoveProjectFromCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.removeProjectFromCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * updateCollection
     */
    async updateCollectionRaw(requestParameters: UpdateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling updateCollection().'
            );
        }

        if (requestParameters['UpdateCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'UpdateCollectionRequest',
                'Required parameter "UpdateCollectionRequest" was null or undefined when calling updateCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/collections/{collectionId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['UpdateCollectionRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * updateCollection
     */
    async updateCollection(requestParameters: UpdateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.updateCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
