/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SignIn200Response,
} from '../models/index';

export interface GetChildResourceRequest {
    fileId: string;
    suffix: string;
}

export interface MarkForDeletionRequest {
    fileId: string;
}

/**
 * FilesApi - interface
 * 
 * @export
 * @interface FilesApiInterface
 */
export interface FilesApiInterface {
    /**
     * 
     * @summary getChildResource
     * @param {string} fileId 
     * @param {string} suffix 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    getChildResourceRaw(requestParameters: GetChildResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * getChildResource
     */
    getChildResource(requestParameters: GetChildResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary markForDeletion
     * @param {string} fileId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    markForDeletionRaw(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * markForDeletion
     */
    markForDeletion(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI implements FilesApiInterface {

    /**
     * getChildResource
     */
    async getChildResourceRaw(requestParameters: GetChildResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getChildResource().'
            );
        }

        if (requestParameters['suffix'] == null) {
            throw new runtime.RequiredError(
                'suffix',
                'Required parameter "suffix" was null or undefined when calling getChildResource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/files/{fileId}/{suffix}`.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId']))).replace(`{${"suffix"}}`, encodeURIComponent(String(requestParameters['suffix']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * getChildResource
     */
    async getChildResource(requestParameters: GetChildResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getChildResourceRaw(requestParameters, initOverrides);
    }

    /**
     * markForDeletion
     */
    async markForDeletionRaw(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling markForDeletion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/files/{fileId}`.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * markForDeletion
     */
    async markForDeletion(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.markForDeletionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
