/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateUploadUrl200Response,
  GetAccessUrl200Response,
  SignIn200Response,
} from '../models/index';

export interface CreateUploadUrlRequest {
    fileName: string;
    contentType: string;
    sha256: string;
}

export interface GetAccessUrlRequest {
    sha256: string;
    preview?: boolean;
}

export interface MarkForDeletionRequest {
    sha256: string;
}

/**
 * FilesApi - interface
 * 
 * @export
 * @interface FilesApiInterface
 */
export interface FilesApiInterface {
    /**
     * 
     * @summary createUploadUrl
     * @param {string} fileName 
     * @param {string} contentType 
     * @param {string} sha256 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    createUploadUrlRaw(requestParameters: CreateUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateUploadUrl200Response>>;

    /**
     * createUploadUrl
     */
    createUploadUrl(requestParameters: CreateUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateUploadUrl200Response>;

    /**
     * 
     * @summary getAccessUrl
     * @param {string} sha256 
     * @param {boolean} [preview] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    getAccessUrlRaw(requestParameters: GetAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAccessUrl200Response>>;

    /**
     * getAccessUrl
     */
    getAccessUrl(requestParameters: GetAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAccessUrl200Response>;

    /**
     * 
     * @summary markForDeletion
     * @param {string} sha256 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    markForDeletionRaw(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * markForDeletion
     */
    markForDeletion(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI implements FilesApiInterface {

    /**
     * createUploadUrl
     */
    async createUploadUrlRaw(requestParameters: CreateUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateUploadUrl200Response>> {
        if (requestParameters['fileName'] == null) {
            throw new runtime.RequiredError(
                'fileName',
                'Required parameter "fileName" was null or undefined when calling createUploadUrl().'
            );
        }

        if (requestParameters['contentType'] == null) {
            throw new runtime.RequiredError(
                'contentType',
                'Required parameter "contentType" was null or undefined when calling createUploadUrl().'
            );
        }

        if (requestParameters['sha256'] == null) {
            throw new runtime.RequiredError(
                'sha256',
                'Required parameter "sha256" was null or undefined when calling createUploadUrl().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fileName'] != null) {
            queryParameters['fileName'] = requestParameters['fileName'];
        }

        if (requestParameters['contentType'] != null) {
            queryParameters['contentType'] = requestParameters['contentType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/files/{sha256}`.replace(`{${"sha256"}}`, encodeURIComponent(String(requestParameters['sha256']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * createUploadUrl
     */
    async createUploadUrl(requestParameters: CreateUploadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateUploadUrl200Response> {
        const response = await this.createUploadUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getAccessUrl
     */
    async getAccessUrlRaw(requestParameters: GetAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAccessUrl200Response>> {
        if (requestParameters['sha256'] == null) {
            throw new runtime.RequiredError(
                'sha256',
                'Required parameter "sha256" was null or undefined when calling getAccessUrl().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['preview'] != null) {
            queryParameters['preview'] = requestParameters['preview'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/files/{sha256}`.replace(`{${"sha256"}}`, encodeURIComponent(String(requestParameters['sha256']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getAccessUrl
     */
    async getAccessUrl(requestParameters: GetAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAccessUrl200Response> {
        const response = await this.getAccessUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * markForDeletion
     */
    async markForDeletionRaw(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['sha256'] == null) {
            throw new runtime.RequiredError(
                'sha256',
                'Required parameter "sha256" was null or undefined when calling markForDeletion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/files/{sha256}`.replace(`{${"sha256"}}`, encodeURIComponent(String(requestParameters['sha256']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * markForDeletion
     */
    async markForDeletion(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.markForDeletionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
