/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAccessUrl200Response,
  GetUploadUrl200Response,
  GetUploadUrlRequest,
  SignIn200Response,
} from '../models/index';

export interface GetAccessUrlRequest {
    fileId: string;
}

export interface GetUploadUrlOperationRequest {
    GetUploadUrlRequest: GetUploadUrlRequest;
}

export interface MarkForDeletionRequest {
    fileId: string;
}

/**
 * FilesApi - interface
 * 
 * @export
 * @interface FilesApiInterface
 */
export interface FilesApiInterface {
    /**
     * 
     * @summary getAccessUrl
     * @param {string} fileId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    getAccessUrlRaw(requestParameters: GetAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAccessUrl200Response>>;

    /**
     * getAccessUrl
     */
    getAccessUrl(requestParameters: GetAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAccessUrl200Response>;

    /**
     * 
     * @summary getUploadUrl
     * @param {GetUploadUrlRequest} GetUploadUrlRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    getUploadUrlRaw(requestParameters: GetUploadUrlOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUploadUrl200Response>>;

    /**
     * getUploadUrl
     */
    getUploadUrl(requestParameters: GetUploadUrlOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUploadUrl200Response>;

    /**
     * 
     * @summary markForDeletion
     * @param {string} fileId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    markForDeletionRaw(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * markForDeletion
     */
    markForDeletion(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI implements FilesApiInterface {

    /**
     * getAccessUrl
     */
    async getAccessUrlRaw(requestParameters: GetAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAccessUrl200Response>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getAccessUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/files/{fileId}`.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getAccessUrl
     */
    async getAccessUrl(requestParameters: GetAccessUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAccessUrl200Response> {
        const response = await this.getAccessUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getUploadUrl
     */
    async getUploadUrlRaw(requestParameters: GetUploadUrlOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUploadUrl200Response>> {
        if (requestParameters['GetUploadUrlRequest'] == null) {
            throw new runtime.RequiredError(
                'GetUploadUrlRequest',
                'Required parameter "GetUploadUrlRequest" was null or undefined when calling getUploadUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/files`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['GetUploadUrlRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getUploadUrl
     */
    async getUploadUrl(requestParameters: GetUploadUrlOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUploadUrl200Response> {
        const response = await this.getUploadUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * markForDeletion
     */
    async markForDeletionRaw(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling markForDeletion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/files/{fileId}`.replace(`{${"fileId"}}`, encodeURIComponent(String(requestParameters['fileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * markForDeletion
     */
    async markForDeletion(requestParameters: MarkForDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.markForDeletionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
