/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateIssueRequest,
  CreateIssueResponse,
  SignIn200Response,
} from '../models/index';

export interface CreateIssueOperationRequest {
    CreateIssueRequest: CreateIssueRequest;
}

export interface ResolveIssueRequest {
    issueId: string;
}

/**
 * IssuesApi - interface
 * 
 * @export
 * @interface IssuesApiInterface
 */
export interface IssuesApiInterface {
    /**
     * 
     * @summary createIssue
     * @param {CreateIssueRequest} CreateIssueRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuesApiInterface
     */
    createIssueRaw(requestParameters: CreateIssueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateIssueResponse>>;

    /**
     * createIssue
     */
    createIssue(requestParameters: CreateIssueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateIssueResponse>;

    /**
     * 
     * @summary resolveIssue
     * @param {string} issueId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IssuesApiInterface
     */
    resolveIssueRaw(requestParameters: ResolveIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * resolveIssue
     */
    resolveIssue(requestParameters: ResolveIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

}

/**
 * 
 */
export class IssuesApi extends runtime.BaseAPI implements IssuesApiInterface {

    /**
     * createIssue
     */
    async createIssueRaw(requestParameters: CreateIssueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateIssueResponse>> {
        if (requestParameters['CreateIssueRequest'] == null) {
            throw new runtime.RequiredError(
                'CreateIssueRequest',
                'Required parameter "CreateIssueRequest" was null or undefined when calling createIssue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/issues`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['CreateIssueRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * createIssue
     */
    async createIssue(requestParameters: CreateIssueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateIssueResponse> {
        const response = await this.createIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * resolveIssue
     */
    async resolveIssueRaw(requestParameters: ResolveIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['issueId'] == null) {
            throw new runtime.RequiredError(
                'issueId',
                'Required parameter "issueId" was null or undefined when calling resolveIssue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/issues/{issueId}`.replace(`{${"issueId"}}`, encodeURIComponent(String(requestParameters['issueId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * resolveIssue
     */
    async resolveIssue(requestParameters: ResolveIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.resolveIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
