/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateIssue200Response,
  CreateIssueRequest,
  CreateProject200Response,
  CreateProjectRequest,
  Project,
  ProjectDetails,
  SignIn200Response,
  UpdateProjectRequest,
  UserData,
} from '../models/index';

export interface AddAssetToProjectRequest {
    tag: AddAssetToProjectTagEnum;
    projectId: string;
    assetId: string;
}

export interface AddFileToProjectRequest {
    projectId: string;
    tag: string;
    sha256: string;
    path?: string;
    fileName?: string;
}

export interface AddUserToProjectRequest {
    projectId: string;
    userId: string;
}

export interface CreateIssueOperationRequest {
    projectId: string;
    CreateIssueRequest: CreateIssueRequest;
}

export interface CreateProjectOperationRequest {
    CreateProjectRequest: CreateProjectRequest;
}

export interface DeleteProjectRequest {
    projectId: string;
}

export interface GetIssuesRequest {
    projectId: string;
}

export interface GetProjectDetailsRequest {
    projectId: string;
}

export interface GetProjectFilesRequest {
    projectId: string;
}

export interface GetProjectMembersRequest {
    projectId: string;
}

export interface RemoveAssetFromProjectRequest {
    tag: RemoveAssetFromProjectTagEnum;
    projectId: string;
    assetId: string;
}

export interface RemoveFileFromProjectRequest {
    projectId: string;
    tag: string;
    sha256: string;
}

export interface RemoveUserFromProjectRequest {
    projectId: string;
    userId: string;
}

export interface ResolveIssueRequest {
    projectId: string;
    issueId: string;
}

export interface UpdateProjectOperationRequest {
    projectId: string;
    UpdateProjectRequest?: UpdateProjectRequest;
}

/**
 * ProjectsApi - interface
 * 
 * @export
 * @interface ProjectsApiInterface
 */
export interface ProjectsApiInterface {
    /**
     * 
     * @summary addAssetToProject
     * @param {'accepted' | 'rejected' | 'pending-review' | 'misc'} tag 
     * @param {string} projectId 
     * @param {string} assetId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    addAssetToProjectRaw(requestParameters: AddAssetToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * addAssetToProject
     */
    addAssetToProject(requestParameters: AddAssetToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary addFileToProject
     * @param {string} projectId 
     * @param {string} tag 
     * @param {string} sha256 
     * @param {string} [path] 
     * @param {string} [fileName] 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    addFileToProjectRaw(requestParameters: AddFileToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * addFileToProject
     * @deprecated
     */
    addFileToProject(requestParameters: AddFileToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary addUserToProject
     * @param {string} projectId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    addUserToProjectRaw(requestParameters: AddUserToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * addUserToProject
     */
    addUserToProject(requestParameters: AddUserToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary createIssue
     * @param {string} projectId 
     * @param {CreateIssueRequest} CreateIssueRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createIssueRaw(requestParameters: CreateIssueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateIssue200Response>>;

    /**
     * createIssue
     */
    createIssue(requestParameters: CreateIssueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateIssue200Response>;

    /**
     * 
     * @summary createProject
     * @param {CreateProjectRequest} CreateProjectRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    createProjectRaw(requestParameters: CreateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateProject200Response>>;

    /**
     * createProject
     */
    createProject(requestParameters: CreateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateProject200Response>;

    /**
     * 
     * @summary deleteProject
     * @param {string} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    deleteProjectRaw(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * deleteProject
     */
    deleteProject(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary getIssues
     * @param {string} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getIssuesRaw(requestParameters: GetIssuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * getIssues
     */
    getIssues(requestParameters: GetIssuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary getProjectDetails
     * @param {string} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectDetailsRaw(requestParameters: GetProjectDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetails>>;

    /**
     * getProjectDetails
     */
    getProjectDetails(requestParameters: GetProjectDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetails>;

    /**
     * 
     * @summary getProjectFiles
     * @param {string} projectId 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectFilesRaw(requestParameters: GetProjectFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * getProjectFiles
     * @deprecated
     */
    getProjectFiles(requestParameters: GetProjectFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary getProjectMembers
     * @param {string} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectMembersRaw(requestParameters: GetProjectMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserData>>>;

    /**
     * getProjectMembers
     */
    getProjectMembers(requestParameters: GetProjectMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserData>>;

    /**
     * 
     * @summary getProjects
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    getProjectsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>>;

    /**
     * getProjects
     */
    getProjects(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>>;

    /**
     * 
     * @summary removeAssetFromProject
     * @param {'accepted' | 'rejected' | 'pending-review' | 'misc'} tag 
     * @param {string} projectId 
     * @param {string} assetId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    removeAssetFromProjectRaw(requestParameters: RemoveAssetFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * removeAssetFromProject
     */
    removeAssetFromProject(requestParameters: RemoveAssetFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary removeFileFromProject
     * @param {string} projectId 
     * @param {string} tag 
     * @param {string} sha256 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    removeFileFromProjectRaw(requestParameters: RemoveFileFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * removeFileFromProject
     * @deprecated
     */
    removeFileFromProject(requestParameters: RemoveFileFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary removeUserFromProject
     * @param {string} projectId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    removeUserFromProjectRaw(requestParameters: RemoveUserFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * removeUserFromProject
     */
    removeUserFromProject(requestParameters: RemoveUserFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary resolveIssue
     * @param {string} projectId 
     * @param {string} issueId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    resolveIssueRaw(requestParameters: ResolveIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>>;

    /**
     * resolveIssue
     */
    resolveIssue(requestParameters: ResolveIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response>;

    /**
     * 
     * @summary updateProject
     * @param {string} projectId 
     * @param {UpdateProjectRequest} [UpdateProjectRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectsApiInterface
     */
    updateProjectRaw(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateProject200Response>>;

    /**
     * updateProject
     */
    updateProject(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateProject200Response>;

}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI implements ProjectsApiInterface {

    /**
     * addAssetToProject
     */
    async addAssetToProjectRaw(requestParameters: AddAssetToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling addAssetToProject().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addAssetToProject().'
            );
        }

        if (requestParameters['assetId'] == null) {
            throw new runtime.RequiredError(
                'assetId',
                'Required parameter "assetId" was null or undefined when calling addAssetToProject().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/assets/{assetId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters['assetId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * addAssetToProject
     */
    async addAssetToProject(requestParameters: AddAssetToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.addAssetToProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * addFileToProject
     * @deprecated
     */
    async addFileToProjectRaw(requestParameters: AddFileToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addFileToProject().'
            );
        }

        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling addFileToProject().'
            );
        }

        if (requestParameters['sha256'] == null) {
            throw new runtime.RequiredError(
                'sha256',
                'Required parameter "sha256" was null or undefined when calling addFileToProject().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['fileName'] != null) {
            queryParameters['fileName'] = requestParameters['fileName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/files/{tag}/{sha256}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"tag"}}`, encodeURIComponent(String(requestParameters['tag']))).replace(`{${"sha256"}}`, encodeURIComponent(String(requestParameters['sha256']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * addFileToProject
     * @deprecated
     */
    async addFileToProject(requestParameters: AddFileToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.addFileToProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * addUserToProject
     */
    async addUserToProjectRaw(requestParameters: AddUserToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addUserToProject().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling addUserToProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/users/{userId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * addUserToProject
     */
    async addUserToProject(requestParameters: AddUserToProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.addUserToProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * createIssue
     */
    async createIssueRaw(requestParameters: CreateIssueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateIssue200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createIssue().'
            );
        }

        if (requestParameters['CreateIssueRequest'] == null) {
            throw new runtime.RequiredError(
                'CreateIssueRequest',
                'Required parameter "CreateIssueRequest" was null or undefined when calling createIssue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects/{projectId}/issues`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['CreateIssueRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * createIssue
     */
    async createIssue(requestParameters: CreateIssueOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateIssue200Response> {
        const response = await this.createIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * createProject
     */
    async createProjectRaw(requestParameters: CreateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateProject200Response>> {
        if (requestParameters['CreateProjectRequest'] == null) {
            throw new runtime.RequiredError(
                'CreateProjectRequest',
                'Required parameter "CreateProjectRequest" was null or undefined when calling createProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['CreateProjectRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * createProject
     */
    async createProject(requestParameters: CreateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateProject200Response> {
        const response = await this.createProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * deleteProject
     */
    async deleteProjectRaw(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * deleteProject
     */
    async deleteProject(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.deleteProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getIssues
     */
    async getIssuesRaw(requestParameters: GetIssuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getIssues().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/issues`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * getIssues
     */
    async getIssues(requestParameters: GetIssuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getIssuesRaw(requestParameters, initOverrides);
    }

    /**
     * getProjectDetails
     */
    async getProjectDetailsRaw(requestParameters: GetProjectDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetails>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getProjectDetails
     */
    async getProjectDetails(requestParameters: GetProjectDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetails> {
        const response = await this.getProjectDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getProjectFiles
     * @deprecated
     */
    async getProjectFilesRaw(requestParameters: GetProjectFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectFiles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/files`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * getProjectFiles
     * @deprecated
     */
    async getProjectFiles(requestParameters: GetProjectFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getProjectFilesRaw(requestParameters, initOverrides);
    }

    /**
     * getProjectMembers
     */
    async getProjectMembersRaw(requestParameters: GetProjectMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserData>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/users`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getProjectMembers
     */
    async getProjectMembers(requestParameters: GetProjectMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserData>> {
        const response = await this.getProjectMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * getProjects
     */
    async getProjectsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Project>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * getProjects
     */
    async getProjects(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Project>> {
        const response = await this.getProjectsRaw(initOverrides);
        return await response.value();
    }

    /**
     * removeAssetFromProject
     */
    async removeAssetFromProjectRaw(requestParameters: RemoveAssetFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling removeAssetFromProject().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling removeAssetFromProject().'
            );
        }

        if (requestParameters['assetId'] == null) {
            throw new runtime.RequiredError(
                'assetId',
                'Required parameter "assetId" was null or undefined when calling removeAssetFromProject().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/assets/{assetId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters['assetId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * removeAssetFromProject
     */
    async removeAssetFromProject(requestParameters: RemoveAssetFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.removeAssetFromProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * removeFileFromProject
     * @deprecated
     */
    async removeFileFromProjectRaw(requestParameters: RemoveFileFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling removeFileFromProject().'
            );
        }

        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling removeFileFromProject().'
            );
        }

        if (requestParameters['sha256'] == null) {
            throw new runtime.RequiredError(
                'sha256',
                'Required parameter "sha256" was null or undefined when calling removeFileFromProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/files/{tag}/{sha256}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"tag"}}`, encodeURIComponent(String(requestParameters['tag']))).replace(`{${"sha256"}}`, encodeURIComponent(String(requestParameters['sha256']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * removeFileFromProject
     * @deprecated
     */
    async removeFileFromProject(requestParameters: RemoveFileFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.removeFileFromProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * removeUserFromProject
     */
    async removeUserFromProjectRaw(requestParameters: RemoveUserFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling removeUserFromProject().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeUserFromProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/users/{userId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * removeUserFromProject
     */
    async removeUserFromProject(requestParameters: RemoveUserFromProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.removeUserFromProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * resolveIssue
     */
    async resolveIssueRaw(requestParameters: ResolveIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignIn200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling resolveIssue().'
            );
        }

        if (requestParameters['issueId'] == null) {
            throw new runtime.RequiredError(
                'issueId',
                'Required parameter "issueId" was null or undefined when calling resolveIssue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/issues/{issueId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))).replace(`{${"issueId"}}`, encodeURIComponent(String(requestParameters['issueId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * resolveIssue
     */
    async resolveIssue(requestParameters: ResolveIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignIn200Response> {
        const response = await this.resolveIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * updateProject
     */
    async updateProjectRaw(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateProject200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects/{projectId}`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['UpdateProjectRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * updateProject
     */
    async updateProject(requestParameters: UpdateProjectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateProject200Response> {
        const response = await this.updateProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AddAssetToProjectTagEnum = {
    accepted: 'accepted',
    rejected: 'rejected',
    pending_review: 'pending-review',
    misc: 'misc'
} as const;
export type AddAssetToProjectTagEnum = typeof AddAssetToProjectTagEnum[keyof typeof AddAssetToProjectTagEnum];
/**
 * @export
 */
export const RemoveAssetFromProjectTagEnum = {
    accepted: 'accepted',
    rejected: 'rejected',
    pending_review: 'pending-review',
    misc: 'misc'
} as const;
export type RemoveAssetFromProjectTagEnum = typeof RemoveAssetFromProjectTagEnum[keyof typeof RemoveAssetFromProjectTagEnum];
